# Generated by Django 4.1.4 on 2023-01-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_account_delete_filelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='faviorates',
            field=models.ManyToManyField(to='main.game'),
        ),
        migrations.AddField(
            model_name='game',
            name='is_available_on_desktop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='is_available_on_mobile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='is_available_on_tablet',
            field=models.BooleanField(default=False),
        ),
    ]
