# Generated by Django 4.1.4 on 2023-01-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_account_faviorates_game_is_available_on_desktop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
