# Generated by Django 4.1.4 on 2023-01-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_game_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='faviorates',
            field=models.ManyToManyField(blank=True, null=True, to='main.game'),
        ),
    ]
