# Generated by Django 4.1.4 on 2023-02-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_ipmodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_developer',
            field=models.BooleanField(default=False),
        ),
    ]
