# Generated by Django 4.1.4 on 2023-02-08 05:09

from django.db import migrations, models
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_account_is_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=main.utils.user_profile_picture_path),
        ),
    ]
