# Generated by Django 4.1.4 on 2023-03-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_socialmedialink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedialink',
            name='link',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='socialmedialink',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
