# Generated by Django 4.1.4 on 2023-04-05 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0015_account_instagram_link_account_linkedin_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='account',
            name='linkedin_link',
        ),
        migrations.RemoveField(
            model_name='account',
            name='twitter_link',
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_social_media_link', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
