# Generated by Django 4.1.4 on 2023-04-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_account_instagram_link_account_linkedin_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='github_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
