# Generated by Django 4.1.4 on 2023-06-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
